### PR TITLE
Web image optimizations

### PR DESCRIPTION
**Pull request by pesickadavid**
@OPesicka please look at the changes with your desinger eye, if everything looks good.
Managed to score some pretty good size savings, with (IMO) minimal perceivable difference.

Before:
image

After:
image

### CODE REVIEW

**Comment by OPesicka** [comment]
Looks good to me. But how is this meant to be used?

Do I need to convert to webp somewhere or will we add some auto conversion on build?

**Comment by VojtechVidra** [comment]
Sorry, I think I wasn't specific enough in the task. I would like the images that are now imported to move from `public` folder to `src` folder, next to the component that is using them. This will make the imports nicer as well as minimize unused files when we'll be removing them in the future.

For the webp file format, I didn't write it down, but in my opinion its better to leave the source files in `png` because it is additional step for development. Let's leave the images in webp and new images can be either webp or png.

**Comment by pesickadavid** [comment]
I've colocated the images with components. Homepage should now be loading a lot faster, or at least the images are lot smaller.
In the latest 30a2772 commit there is also updated metadata for `/features` routes @OPesicka  check if it's okay

**Comment by pesickadavid** [comment]
The placeholder "blur" looks ugly on images with transparency, resulting in noticeable jump from the blurry version to full size one.
AVIF format is IMO slow and although it looks better, the added processing needed is not worth it now.

**Pull request merged**
